### PR TITLE
Adding Artistic Style Transfer with GAN

### PR DESCRIPTION
**Pull request by BlueBlaze6335**
#69

### CODE REVIEW

**Comment by BlueBlaze6335** [comment]
@smaranjitghose  having a problem regarding squashing the commits. Can you please help ?!

**Comment by smaranjitghose** [comment]
> @smaranjitghose having a problem regarding squashing the commits. Can you please help ?!

Refer [this](https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc)

**Comment by smaranjitghose** [comment]
Read the PR [guidelines](https://github.com/smaranjitghose/ArtCV/pull/68)

**Comment by BlueBlaze6335** [comment]
Dear @smaranjitghose ,
I have squashed the commits using rebase  !!
The link to the colab notebook-   https://colab.research.google.com/drive/121NTaq0OX1BkjGccoRAn1dD1b1HIIWEl#scrollTo=a785SVuMtIzH

I have introduced a cell of code in the notebook , where a user can put the image address of their own choice and generate Stylized image.  However GANS can only generate one style of image that it has been trained upon. So adding a style image is of no use. I have explained my work in the notebook , and have given a synopsis of the project in the readme (in the format you have stated!!) as well as a link to the notebook. I have included the python file of the notebook and the notebook for convenience and have also changed folder name images to "assets". I think this makes the work absolutely eligible for merging. 

Regards , 
Padmanabha Banerjee.

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Some reordering of files is still required. No worries, I'll take care of it later

**Pull request merged**
